import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type React from "react";

import "@/styles/global.css";
import "@/app/globals.css";

import RootLayoutProvider from "@/components/providers/RootLayoutProvider";
import Header from "@/components/common/layout/Header";
import Sidebar from "@/components/common/layout/Sidebar";
import Footer from "@/components/common/layout/Footer";
import Toast from "@/components/common/layout/Toast";
import ConfirmModal from "@/components/common/layout/ConfirmModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "사랑의교회 대학부",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={inter.className}>
        <RootLayoutProvider>
<<<<<<< Updated upstream:src/app/(main)/layout.tsx
        <Header />
        <div className="flex min-h-screen relative">
          <Sidebar />
          <main className="flex-1 overflow-x-hidden">{children}</main>
        </div>
        <Footer />
        <Toast />
        <ConfirmModal />
=======
          <Header />
          <div className="flex min-h-screen">
            <Sidebar />
            <main className="flex-1">{children}</main>
          </div>
          <Footer />
          <Toast />
          <ConfirmModal />
>>>>>>> Stashed changes:src/app/layout.tsx
        </RootLayoutProvider>
      </body>
    </html>
  );
}
