import type { Metadata } from "next"
import { Inter } from "next/font/google"
import type React from "react"

import "@/styles/global.css"
import "@/app/globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "사랑의교회 대학부",
  description: "Generated by create next app",
}

/**
 * Root Layout - Server Component
 * Next.js 필수 최상위 레이아웃
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${inter.className} overflow-x-hidden`}>
        {children}
      </body>
    </html>
  )
}
